### ISSUE TITLE
Potential incorrect warning when storing a delegate value of a property in a local variable

### ISSUE THREAD

**Issue by EnCey** [controlflow/resharper-heapview#113] opened 2023-04-19 10:57 UTC
Given a property of a delegate type (`Func`, `Predicate` etc.), I get a warning when storing the value of that property in a local variable.
To my knowledge, and after checking the IL code (which I'm not that familiar with), I don't think an allocation is happening.

As I understand things, a reference to the delegate is returned and stored in the variable, no allocation should happen.
Also I do NOT get a warning when directly invoking the property, only when first storing it in a variable, which also seems odd.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/1894528/233054185-5945295f-0dc1-4857-a3d4-69d4453baefe.png">

```cs
public class Holder
{
  public Predicate<int> Checker { get; init; }
}

public class Tester
{
  public bool Test()
  {
    var holder = new Holder {
      Checker = x => x > 1
    };
    return Use(holder, 5);
  }

  public bool Use(Holder h, int arg)
  {
    var local = h.Checker;
    return local(arg);
  }
}
```

**Comment by controlflow** [comment] 2023-06-14 15:05
Should be fixed in 103fe4d133944c22e26b2abad536cbd24df0df50 I cannot reproduce this in latest builds

**Closed by controlflow** 2023-06-14 15:05 UTC
